In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.datasets import load_iris
iris_dataset = load_iris()

In [3]:
type(iris_dataset)

sklearn.utils._bunch.Bunch

In [4]:
iris_dataset.DESCR

'.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ============== ==== =

In [5]:
iris_dataset.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [6]:
iris_dataset.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [7]:
iris_dataset.data.shape

(150, 4)

In [8]:
x_feature = iris_dataset.data

In [9]:
y_target = iris_dataset.target

In [10]:
print(x_feature.shape)

(150, 4)


In [11]:
y_target.shape

(150,)

In [27]:
from sklearn.neighbors import KNeighborsClassifier

In [28]:
classifier = KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2)

In [29]:
classifier.fit(x_feature, y_target)

KNeighborsClassifier()

In [30]:
import numpy as nm  
import matplotlib.pyplot as mtp  
import pandas as pd

In [42]:
from sklearn.datasets import load_iris
iris_dataset = load_iris()
print(iris_dataset)

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [44]:
x= iris_dataset.iloc[:, [1,2]].values  
y= iris_dataset.iloc[:, 3].values 

AttributeError: iloc

How to use the k-means clustering 

In [1]:
import numpy as np

In [2]:
from sklearn.cluster import KMeans

In [4]:
from sklearn.datasets import make_blobs #random sample generators 

In [5]:
n_samples = 200

In [6]:
random_state = 20

In [7]:
X, y = make_blobs(n_samples=n_samples, n_features=5, random_state=None)

In [8]:
predict_y = KMeans(n_clusters=3, random_state=random_state).fit_predict(X)

In [9]:
predict_y

array([2, 0, 2, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 2, 2, 1, 1, 2, 0, 2, 1, 0,
       2, 1, 2, 1, 2, 1, 1, 2, 1, 0, 2, 1, 0, 0, 0, 2, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 2, 1, 1, 0, 2, 1, 2, 2, 1, 2, 2, 1, 2, 0, 1, 2, 2, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 2, 1, 1, 2, 0, 1, 1, 2, 2, 0, 1, 1, 2, 0,
       2, 1, 0, 1, 0, 2, 1, 2, 1, 1, 0, 0, 1, 1, 2, 0, 0, 0, 1, 1, 2, 0,
       0, 2, 1, 0, 2, 2, 1, 0, 1, 2, 1, 1, 2, 0, 2, 1, 0, 1, 0, 0, 1, 2,
       0, 2, 1, 1, 2, 2, 0, 2, 0, 0, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2, 1, 0,
       0, 2, 1, 0, 2, 1, 0, 0, 1, 0, 1, 2, 1, 0, 0, 2, 2, 2, 2, 2, 2, 1,
       2, 0, 1, 2, 2, 1, 2, 0, 0, 1, 0, 1, 2, 1, 0, 0, 2, 1, 2, 0, 2, 0,
       0, 1], dtype=int32)

DEMO PCA TO REDUCE THE DIMENSIONALITY OF DATASET

In [10]:
from sklearn.decomposition import PCA

In [11]:
from sklearn.datasets import make_blobs

In [13]:
n_samples = 200
random_state = 20

In [14]:
X , y = make_blobs(n_samples=n_samples, n_features=10, random_state=None)

In [15]:
X.shape

(200, 10)

In [16]:
pca = PCA(n_components=3)

In [21]:
pca.fit(X)
pca.explained_variance_ratio_

array([0.65590639, 0.31858549, 0.00382062])

In [22]:
first_pca = pca.components_[0]
first_pca

array([-0.02526723, -0.29844198, -0.37859036,  0.01994457, -0.43839798,
        0.20596894, -0.49425059,  0.37571774, -0.16806933, -0.34388189])

In [23]:
pca_reduce = pca.transform(X)

In [25]:
pca_reduce.shape

(200, 3)

HOW TO BUILD THE PIPELINE FOR MORE THEN ONE INSTANCES USING SCIKIT

In [35]:
import sklearn

In [36]:
from sklearn.pipeline import Pipeline

In [37]:
from sklearn.linear_model import LinearRegression

In [38]:
from sklearn.decomposition import PCA

In [39]:
estimator = [('dim_reduction',PCA()),('linear_model', LinearRegression())]

In [43]:
 pipeline_esstimator = Pipeline(estimator)

In [44]:
pipeline_esstimator

Pipeline(steps=[('dim_reduction', PCA()), ('linear_model', LinearRegression())])

In [45]:
pipeline_esstimator.steps[0]

('dim_reduction', PCA())

In [46]:
pipeline_esstimator.steps[1]

('linear_model', LinearRegression())

In [47]:
pipeline_esstimator.steps

[('dim_reduction', PCA()), ('linear_model', LinearRegression())]